#!/usr/bin/env bash

if [[ "${2}x" != "x" && "${2}x" != "x" ]]; then
  while true; do
    mpv ${1} --title="radio-mpv" ${2} --no-video \
      --ytdl-raw-options=cookies-from-browser=firefox
  done
fi
